apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  labels:
    app: mydeploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mydeploy
  template:
    metadata:
      labels:
        app: mydeploy
    spec:
      containers:
      - name: myapp
        image: nginx
        volumeMounts:
        - name: myvolume
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: myvolume
        configMap:
          name: myindex